- name: Get AKS private FQDN
  shell: az aks show --resource-group "{{ resource_group }}" --name "{{ cluster_name }}" --query "privateFqdn" -o tsv
  register: aks_private_fqdn
  changed_when: false

- name: Get private endpoint resource ID
  shell: az network private-endpoint list --resource-group "{{ resource_group }}" --query "[0].id" -o tsv
  register: private_endpoint_id
  changed_when: false

- name: Get NIC ID from private endpoint
  shell: az network private-endpoint show --ids "{{ private_endpoint_id.stdout }}" --query "networkInterfaces[0].id" -o tsv
  register: nic_id
  changed_when: false

- name: Get private IP from NIC
  shell: az network nic show --ids "{{ nic_id.stdout }}" --query "ipConfigurations[0].privateIpAddress" -o tsv
  register: private_ip
  changed_when: false

- name: Add AKS private endpoint to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ private_ip.stdout }} {{ aks_private_fqdn.stdout }}"
    state: present
  when: private_ip.stdout != "